sudo: false

language: python
python:
  - "2.7"
  - "3.2"

cache:
  apt: true

addons:
  apt:
    packages:
      - python-scipy
      - python3-scipy

virtualenv:
  system_site_packages: true

script: nosetests -v --with-doctest
