sudo: false

language: python
python:
  - "2.7"
  - "3.5"

cache:
  apt: true

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libfftpack-dev
      - gfortran

script: nosetests -v --with-doctest
