sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

cache:
  apt: true

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - python-scipy

script: nosetests -v --with-doctest
